### ISSUE TITLE
Labels 

### ISSUE THREAD

**Issue by amomagus** [WemXPro/tracker#393] opened 2024-02-20 18:25 UTC
### Describe the solution you'd like

Would be nice if you could assign labels to products like: popular

**Comment by PadowYT2** [comment] 2024-02-20 18:33
Duplicate of #132

**Closed by PadowYT2** 2024-02-20 18:33 UTC
Labels: duplicate, enhancement, invalid

**Comment by Mr-sl1d3r** [comment] 2024-02-20 19:36
I solved the problem by doing an implementation in my portal code so I get
![image](https://github.com/WemXPro/tracker/assets/76396365/aa5267a4-b6c8-4895-961f-5d93a33969a9)
