### ISSUE TITLE
Add sub categories in the store.

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#372] opened 2024-02-04 11:55 UTC
### Describe the solution you'd like

Will be interesting to have sub categories in the store so we will have more choices to organise the store.

**Comment by Ariz-z** [comment] 2024-02-05 00:55
yeah its a nice idea

**Comment by VanillaChan6571** [comment] 2024-03-02 16:58
Duplicate of #333

**Closed** 2024-04-10 07:16 UTC
Labels: enhancement
