### ISSUE TITLE
"Go Back" button when verifying email

### ISSUE THREAD

**Issue by VortexxJS** [WemXPro/tracker#412] opened 2024-03-08 22:32 UTC
### Describe the solution you'd like

When i was testing the user registration, i noticed you cant change your registration data once you have started the verification process. It would be very cool to have a Go Back button to change anything if you misstyped the email or anything. Right now you would either need to use another browser or clear your website data (cookies and whatever there is.)

**Comment by PadowYT2** [comment] 2024-03-08 22:34
Duplicate of WemXPro/tracker#278

**Closed by PadowYT2** 2024-03-08 22:34 UTC
Labels: duplicate, enhancement, invalid
