### ISSUE TITLE
Custom Option VPS

### ISSUE THREAD

**Issue by REX-YT** [WemXPro/tracker#291] opened 2023-12-09 19:40 UTC
### Product

WemX

### Describe the solution you'd like

I would suggest that there be more options to configure the proxmox service, such as uploading the cores, the ram, etc. (there is an extra cost), also that the client can put the ISO they want

Also in this part of the code it is poorly done, if in proxmox you do not have the disk that the VM is not created, it should be configurable.

![image](https://github.com/WemXPro/tracker/assets/59341424/93cbb932-494b-412e-a5b7-a543c9ca3fa5)

**Comment by PadowYT2** [comment] 2023-12-09 20:21
Duplicate of #238

**Closed by PadowYT2** 2023-12-09 20:21 UTC
Labels: duplicate, enhancement, wemx

**Comment by Mubeen142** [comment] 2023-12-09 20:57
Hi @REX-YT 

Thank you for reporting this.

I am currently rewriting the proxmox service. You can send me a DM on discord if you want to suggest features
