### ISSUE TITLE
Addional Packages

### ISSUE THREAD

**Issue by amomagus** [WemXPro/tracker#391] opened 2024-02-20 17:33 UTC
### Describe the solution you'd like

So if you buy a package you can also see a Tab Called „Additional Package“ (if you made one only) There instance owners can create a separate package that you can add like „Priority Support“ (my Support Priority Idea) or „Extra Port“ and they would work like special packages that could do things like listed. You could add a Additional Package by going into Products then the Category  and the package then click on edit on the package you want and you will see a tab called „Additional Packages“ you can click on it and it will let you add one or more which would work like a special package in a package (So it could give a extra port) For the Extra port idea owners should be able to let them choose a port (so a text box would be nice).

**Comment by PadowYT2** [comment] 2024-02-20 18:18
Duplicate of #238

**Closed by PadowYT2** 2024-02-20 18:18 UTC
Labels: duplicate, enhancement, invalid
