### ISSUE TITLE
Ticking "Show Author" off doesn't hide author in articles

### ISSUE THREAD

**Issue by HunterShenep** [WemXPro/tracker#400] opened 2024-02-25 18:32 UTC
### Describe the issue

Ticking "Show Author" off doesn't hide author in articles

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

2.0.1

### To Reproduce

1. Admin
2. Articles
3. Open existing or create new Article
4. Show Author in off position doesn't do anything

**Comment by VanillaChan6571** [comment] 2024-03-02 15:49
Cannot Reproduce This Issue. You might have a broken client theme or non-updated client theme. (Would Close This but not a Github Mod)

**Comment by GIGABAIT93** [comment] 2024-03-05 11:38
Will be fixed in the next update

**Closed by GIGABAIT93** 2024-03-05 11:38 UTC
Labels: bug
