### ISSUE TITLE
Contact Us Bug

### ISSUE THREAD

**Issue by Shockingg** [WemXPro/tracker#203] opened 2023-09-14 15:23 UTC
### Product

WemX Pro

### Describe the issue

From my testing, the contact us system just doesn't work whatsoever, emails don't get sent to the contact email, or any other email. I'm using a custom SMTP server if that makes a difference.

### Pterodactyl Panel Version

1.11.3

### Product Version

1.5.0

### To Reproduce

1. Go to contact us page
2. Fill in the fields and click send message
3. It will say the email was sent successfully but it never gets sent.

### Expected Behaviour

Sends an email to the contact email provided in the configuration > settings page in admin panel.

**Comment by VanillaChan6571** [comment] 2023-09-14 15:33
I think its a dummy page because it has no SMTP coding at all for that page. So yeah, contact us does nothing in regards of "submitting an email" 

In the code, its under TODO and will not work. so no its not a bug, just not implemented.
![image](https://github.com/VertisanPRO/pterodactyl/assets/39040261/ba8310b3-0abf-4c72-b06c-57c405bd0d9d)

**Comment by Shockingg** [comment] 2023-09-14 15:34
Oh right, well that explains it.

**Comment by Mubeen142** [comment] 2023-11-29 19:18
Thanks for reporting the issue @Shockingg 

The bug has been fixed once and for all. I have rewritten the code for the contact us page.

Contact us submissions are now also saved in the emails history tab. In addition, I added better measurements such as rate limiters to prevent users / bots from spamming the form. Users can submit forms every 1 to 2 hours now

**Closed by Mubeen142** 2023-11-29 19:18 UTC
Labels: bug, wemx
